Feature/mai finance
defisaver/defisaver-v3-contracts pull request #136
Opened 2022-05-05 14:58 UTC by majkic99

npx hardhat changeRepoNetwork Mainnet Optimism
npx hardhat node (with optimism rpc)
npx hardhat test --network localOptimism test/qidao/...

2022-05-06 11:59 UTC, kjaredic reviewed
looks good, see about mapping vaultId

2022-05-06 11:59 UTC, kjaredic commented on contracts/actions/qidao/QiDaoGenerate.sol
> +        inputData.userVaultId = _parseParamUint(
why not map vaultId as well? could be useful for strategies idk

2022-05-06 11:59 UTC, kjaredic commented on contracts/views/QiDaoView.sol
> +}
It's a view but i see nothing

2022-05-06 11:59 UTC, kjaredic commented on contracts/actions/qidao/QiDaoSupply.sol
> +        collateralAsset.approveToken(vaultAddress, _inputParams.amount);
if amount is uintMax this will give max approval

2022-05-06 12:18 UTC, kjaredic approved these changes
lgtm

2022-05-09 10:58 UTC, yippee-ki-yay commented on contracts/actions/qidao/QiDaoPayback.sol
> +        if (_inputParams.from == address(0)) revert NullAddressTransfer();
No need to check _from == 0x0 as we can't pull tokens from 0x0

2022-05-09 11:02 UTC, yippee-ki-yay commented on contracts/actions/qidao/QiDaoPayback.sol
> +        if (_inputParams.amount == type(uint256).max) {
Take userVault whole debt when the amount sent is bigger than the userVault debt to have the same behaviour as Maker

2022-05-09 11:07 UTC, yippee-ki-yay commented on contracts/actions/qidao/QiDaoSupply.sol
> +        if (_inputParams.from == address(0)) revert NullAddressTransfer();
Same no need to check _from == 0x0

2022-05-09 11:08 UTC, yippee-ki-yay commented on contracts/actions/qidao/QiDaoSupply.sol
> +        _inputParams.amount = collateralAsset.pullTokensIfNeeded(_inputParams.from, _inputParams.amount);
Handle uint.max take the whole balance of _from

2022-05-09 11:18 UTC, yippee-ki-yay commented on contracts/actions/qidao/helpers/QiDaoRegistry.sol
> +    function registerVault(address _vaultAddr) internal returns (uint16 vaultId){
Just a preference but putin the internal method below the removeVault which has permission of onlyOwner

2022-05-09 11:19 UTC, yippee-ki-yay commented on contracts/actions/qidao/helpers/QiDaoRegistry.sol
> +contract QiDaoRegistry is AdminAuth {
Comments on methods and what the contract is for

2022-05-09 11:22 UTC, yippee-ki-yay commented on contracts/actions/qidao/helpers/QiDaoRegistry.sol
> +    mapping(uint16 => address) public vaultAddressById;
Maybe a check when we take vaultAddr as they could be 0x0, currently it isn't a problem as the code will just fail, but a low lvl. call to 0x0 might pass as success and leave some tokens on proxy etc...

2022-05-09 11:25 UTC, yippee-ki-yay commented on test/actions.js
> -const executeAction = async (actionName, functionData, proxy, regAddr = REGISTRY_ADDR) => {
removing regAddr = REGISTRY_ADDR breaks forkoor related stuff which need to inject registry like mcdWithdraw action

2022-05-09 11:29 UTC, yippee-ki-yay commented on test/qidao/qidao-tests.js
> +const hre = require('hardhat');
Test code paths related to uint-max flow

2022-05-09 11:31 UTC, yippee-ki-yay commented on contracts/views/QiDaoView.sol
> +    function getVaultInfo(uint16 _vaultId, uint256 _userVaultId) public view returns (uint256 coll, uint256 debt) {
Not just here but maybe in general don't use `_vaultId` as we are use to meaning a diff. thing in Maker. Instead something like qiVaultId, qiDaoVaultId, collVaultId, etc... something to indicate that it's a protocol wide id.

2022-05-09 11:32 UTC, yippee-ki-yay requested changes
In general the implementation looks good, can further optimize calldata savings and there are a few more edge cases we can cover (notes in comments).

2022-05-13 08:16 UTC, merged