Feature/credit delegation
defisaver/defisaver-v3-contracts pull request #257
Opened 2023-07-31 08:53 UTC by majkic99

getCreditDelegation view helper function currently in action itself, but can be transfered to view if it makes more sense

2023-08-04 14:23 UTC, yippee-ki-yay commented on contracts/actions/spark/SparkDelegateCredit.sol
> +        params.market = _parseParamAddr(params.market, _paramMapping[0], _subData, _returnValues);
wat

2023-08-04 14:29 UTC, yippee-ki-yay commented on contracts/actions/aaveV3/AaveV3DelegateCredit.sol
> +        logger.logActionDirectEvent("SparkDelegateCredit", logData);
AaveV3

2023-08-04 14:30 UTC, yippee-ki-yay reviewed
Few small fixes needed

2023-08-09 13:26 UTC, kjaredic requested changes
lgtm just one small change

2023-10-10 11:44 UTC, yippee-ki-yay commented on test/aaveV3/aave-delegate-credit.js
> +    it('... should run full aave set EMode test', async () => {
Wrong description

2023-10-10 11:49 UTC, yippee-ki-yay approved these changes

2023-10-10 11:49 UTC, yippee-ki-yay approved these changes

2023-10-10 12:42 UTC, merged